# 実行環境から起動するとこれも起動するのか…いや確かに便利だが邪魔になるな。
services:
#  mariadb:
#    image: 'mariadb:latest'
#    environment:
#      - 'MARIADB_DATABASE=mydatabase'
#      - 'MARIADB_PASSWORD=secret'
#      - 'MARIADB_ROOT_PASSWORD=verysecret'
#      - 'MARIADB_USER=myuser'
#    ports:
#      - '3306'

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=verysecret
    ports:
      - "3001:80"
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    ports:
#      - '5432'
