spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dummy
    username: myuser
    password: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
test:
  uri: http://localhost